# Generated by Django 6.0.4 on 2026-04-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Lowercase domain name (e.g. example.com).', max_length=255, unique=True)),
                ('is_exempt', models.BooleanField(db_index=True, default=False, help_text='If True, this domain is explicitly allowed even if it appears in the blocked list. Use this to override seeded entries.')),
                ('source', models.CharField(choices=[('seeded', 'Seeded'), ('custom', 'Custom')], default='custom', help_text='How this entry was created.', max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional operator notes about this entry.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'blocked domain',
                'verbose_name_plural': 'blocked domains',
                'ordering': ['domain'],
            },
        ),
    ]
